name: mydotnet project

on:
  push:
    branches:
      - develop

jobs:
  myjob:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: dotnet version
      uses: actions/setup-dotnet@v4 
      with:
        dotnet-version: "9.0.100"
    - name: this is my dotnet publish command
      run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o demo
    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@v3
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
          args: >
            -Dsonar.organization=manoj723529
            -Dsonar.projectKey=manoj723529_nopCommerce
            -Dsonar.host.url=https://sonarcloud.io
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build Docker image
      env:
        ECR_REGISTRY: aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 772217230642.dkr.ecr.eu-north-1.amazonaws.com
        ECR_REPOSITORY: dev/nop
        IMAGE_TAG: latest
      run: |
        docker build -t dev/nop .
        docker tag dev/nop:latest 772217230642.dkr.ecr.eu-north-1.amazonaws.com/dev/nop:latest
        docker push 772217230642.dkr.ecr.eu-north-1.amazonaws.com/dev/nop:latest
        - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@v0.28.0
      with:
        image-ref: '772217230642.dkr.ecr.eu-north-1.amazonaws.com/dev/nop:latest'
        format: 'table'           
        output: 'trivy-results.xml'
        exit-code: '1'          
        ignore-unfixed: true   
        severity: 'CRITICAL,HIGH' 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-north-1
