name: mydotnet project

on:
  push:
    branches:
      - develop

jobs:
  myjob:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: this is my dotnet publish command
      run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o demo
    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@v3
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
          args: >
            -Dsonar.organization=manoj723529
            -Dsonar.projectKey=manoj723529_nopCommerce
            -Dsonar.host.url=https://sonarcloud.io
